### ISSUE TITLE
Light suppression

### ISSUE THREAD

**Issue by wusiqi521** [jinyeying/night-enhancement#9]
Hi，Sorry to bother you， Looks like you didn't publish the demo. py  ， So I would like to ask if your light suppression work can also play a good role in suppressing glare in the daytime scene

**Comment by jinyeying** [comment]
While our framework is designed for night image enhancement, the unsupervised light-effects suppression network can also work for daytime flare removal since it learns from the unpaired flare/flare-free data shown in Fig.2.
Using constraints specific to daytime to handle remaining problems will be part of our future work.

**Comment by wusiqi521** [comment]
Thank you for your reply, I wonder if you will publish the relevant code for light effect suppression，thank you

**Comment by jinyeying** [comment]
released
